"""add remediations table

Revision ID: 023ad0eb9823
Revises: c0ecf2f76c48
Create Date: 2026-07-27 13:32:44.380368

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '023ad0eb9823'
down_revision: Union[str, None] = 'c0ecf2f76c48'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('remediations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('vulnerability_id', sa.UUID(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('steps', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('reference_links', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('generated_by', sa.String(length=16), nullable=False),
    sa.Column('model_version', sa.String(length=128), nullable=True),
    sa.Column('prompt_version', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['vulnerability_id'], ['vulnerabilities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vulnerability_id', name='uq_remediations_vulnerability')
    )
    op.create_index(op.f('ix_remediations_vulnerability_id'), 'remediations', ['vulnerability_id'], unique=False)
    # ### end Alembic commands ###

    # RLS via vulnerabilities -> projects.workspace_id (2-hop, same pattern as
    # risk_scores/compliance_mappings). No new permissions -- reuses
    # vulnerability:read (GET) and vulnerability:manage (POST generate).
    op.execute("ALTER TABLE remediations ENABLE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE remediations FORCE ROW LEVEL SECURITY")
    op.execute(
        "CREATE POLICY workspace_isolation ON remediations USING ("
        "vulnerability_id IN (SELECT v.id FROM vulnerabilities v JOIN projects p ON p.id = v.project_id "
        "WHERE p.workspace_id = current_setting('app.current_workspace_id', true)::uuid))"
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_remediations_vulnerability_id'), table_name='remediations')
    op.drop_table('remediations')
    # ### end Alembic commands ###
