"""add scans last_heartbeat_at

Executor liveness for the orphan reaper. Purely ADDITIVE: one nullable column on `scans`,
no data migration, no change to any existing column, index, or constraint -- the MySQL
baseline (417cf2df2299) is untouched.

WHY: the reaper previously decided a scan was orphaned from ELAPSED WALL-CLOCK TIME alone
(`started_at` older than a fixed timeout), which cannot tell a healthy 5-hour nuclei/ffuf
run apart from a scan whose worker was SIGKILLed -- so it necessarily either killed
legitimate long scans or left dead ones running. The executor now stamps this column
roughly every 30s while a tool runs, letting the reaper key on LIVENESS instead: no
heartbeat for scan_stale_heartbeat_seconds means genuinely dead, at any runtime.

NULLABLE, deliberately: a just-claimed scan has not ticked yet, and a scan started by an
older build never stamps it. The reaper COALESCEs to `started_at`, so a NULL can never make
a scan immortal. Backfilling was considered and rejected -- it would date rows to the
migration instant, which is meaningless as a liveness signal.

The column type is UTCDateTime (not sa.DateTime): MySQL's DATETIME is timezone-blind and
defaults to second resolution -- see apps/api/core/db_types.py for the full writeup. That
makes this DATETIME(6), consistent with every other timestamp in this schema.

Revision ID: 20d9114ac4ed
Revises: 3c59542f51d4
Create Date: 2026-08-29 02:15:19.783922

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# Autogenerate emits the fully-qualified `apps.api.core.db_types.UTCDateTime()` below but
# does NOT emit this import, so the generated file raises NameError on upgrade without it.
import apps.api.core.db_types


# revision identifiers, used by Alembic.
revision: str = '20d9114ac4ed'
down_revision: Union[str, None] = '3c59542f51d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scans', sa.Column('last_heartbeat_at', apps.api.core.db_types.UTCDateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scans', 'last_heartbeat_at')
    # ### end Alembic commands ###
