"""mysql baseline schema

Phase 0 MySQL cutover: this is a squashed baseline, not an incremental migration. It replaces
25 Postgres-targeted migrations (the CREATE TABLE/ALTER history now archived, not deleted --
see docs/architecture for where) with ONE migration that creates the full current schema
directly against MySQL. It was generated by `alembic revision --autogenerate` diffing an empty
MySQL database against this codebase's SQLAlchemy models (apps.api.core.models_all), then
hand-verified by actually running `alembic upgrade head` against a live MariaDB instance --
not merely eyeballed. This is a clean cutover per project decision: there is no migration path
FROM an existing Postgres database, and no Postgres Row-Level Security is recreated here --
workspace isolation is enforced in the application layer (apps.api.core.tenancy) instead; see
its module docstring for the full rationale.

Every timestamp column uses `apps.api.core.db_types.UTCDateTime()` rather than the raw
`sa.DateTime(timezone=True)` the autogenerate diff first produced: MySQL's DATETIME has no
timezone concept (the dialect silently drops `timezone=True`) and, more subtly, defaults to
0 fractional seconds -- second resolution -- which made "most recent row" queries
(`ORDER BY created_at DESC LIMIT 1`) nondeterministic for rows created within the same
second. UTCDateTime's own docstring has the full empirical writeup; here it means every
DATETIME column below is actually `DATETIME(6)`.

Every `created_at`/timestamp column's `server_default` is `sa.text('CURRENT_TIMESTAMP(6)')`,
not `sa.text('now()')` (what autogenerate originally produced, and what this file shipped with
until this was caught). SQLAlchemy's `func.now()` / literal `now()` compiles fine as a MySQL
*query* expression, but MySQL's DDL grammar only accepts the literal keyword
`CURRENT_TIMESTAMP` (optionally with a fractional-seconds precision matching the column's, hence
`(6)` here to match `DATETIME(6)`) inside a column's `DEFAULT` clause -- `now()` there raises
`(1067, "Invalid default value for '<column>'")`. This baseline's own claim above, that it was
"hand-verified... against a live MariaDB instance," is exactly why it shipped broken: MariaDB's
DDL grammar is more permissive and accepts `DEFAULT now()`, so the bug was invisible against
MariaDB and only surfaced running `alembic upgrade head` against real MySQL 8. The lesson --
MariaDB is NOT a reliable MySQL stand-in for DDL-level syntax, only for most DML/query
behavior -- applies to every other "verified against MariaDB" claim in this codebase's history
too; take them as "verified against a MySQL-family database," not as "verified against MySQL."
Same fix applied to every model's `server_default=func.now()` (apps/api/modules/*/models.py
etc.), which would hit the identical error if this metadata were ever used to emit DDL directly
(e.g. `Base.metadata.create_all()`) instead of through this migration.

Revision ID: 417cf2df2299
Revises:
Create Date: 2026-08-21 14:29:44.123720

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import apps.api.core.db_types


# revision identifiers, used by Alembic.
revision: str = '417cf2df2299'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permissions',
    sa.Column('id', apps.api.core.db_types.GUID(length=36), nullable=False),
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('users',
    sa.Column('id', apps.api.core.db_types.GUID(length=36), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('mfa_enabled', sa.Boolean(), nullable=False),
    sa.Column('mfa_secret_encrypted', sa.Text(), nullable=True),
    sa.Column('mfa_enabled_at', apps.api.core.db_types.UTCDateTime(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', apps.api.core.db_types.UTCDateTime(), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.Column('last_login_at', apps.api.core.db_types.UTCDateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('mfa_recovery_codes',
    sa.Column('id', apps.api.core.db_types.GUID(length=36), nullable=False),
    sa.Column('user_id', apps.api.core.db_types.GUID(length=36), nullable=False),
    sa.Column('code_hash', sa.String(length=64), nullable=False),
    sa.Column('used_at', apps.api.core.db_types.UTCDateTime(), nullable=True),
    sa.Column('created_at', apps.api.core.db_types.UTCDateTime(), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mfa_recovery_codes_code_hash'), 'mfa_recovery_codes', ['code_hash'], unique=True)
    op.create_index(op.f('ix_mfa_recovery_codes_user_id'), 'mfa_recovery_codes', ['user_id'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('id', apps.api.core.db_types.GUID(length=36), nullable=False),
    sa.Column('user_id', apps.api.core.db_types.GUID(length=36), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', apps.api.core.db_types.UTCDateTime(), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.Column('expires_at', apps.api.core.db_types.UTCDateTime(), nullable=False),
    sa.Column('revoked_at', apps.api.core.db_types.UTCDateTime(), nullable=True),
    sa.Column('replaced_by_id', apps.api.core.db_types.GUID(length=36), nullable=True),
    sa.ForeignKeyConstraint(['replaced_by_id'], ['refresh_tokens.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refresh_tokens_token_hash'), 'refresh_tokens', ['token_hash'], unique=True)
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('workspaces',
    sa.Column('id', apps.api.core.db_types.GUID(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('plan_tier', sa.String(length=32), nullable=False),
    sa.Column('owner_user_id', apps.api.core.db_types.GUID(length=36), nullable=False),
    sa.Column('created_at', apps.api.core.db_types.UTCDateTime(), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ai_usage',
    sa.Column('id', apps.api.core.db_types.GUID(length=36), nullable=False),
    sa.Column('workspace_id', apps.api.core.db_types.GUID(length=36), nullable=False),
    sa.Column('scan_id', apps.api.core.db_types.GUID(length=36), nullable=True),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('model', sa.String(length=128), nullable=False),
    sa.Column('agent_role', sa.String(length=64), nullable=True),
    sa.Column('prompt_tokens', sa.Integer(), nullable=False),
    sa.Column('completion_tokens', sa.Integer(), nullable=False),
    sa.Column('estimated_cost_usd', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('correlation_id', sa.String(length=64), nullable=True),
    sa.Column('prompt_version', sa.String(length=64), nullable=True),
    sa.Column('created_at', apps.api.core.db_types.UTCDateTime(), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_usage_created_at'), 'ai_usage', ['created_at'], unique=False)
    op.create_index(op.f('ix_ai_usage_scan_id'), 'ai_usage', ['scan_id'], unique=False)
    op.create_index(op.f('ix_ai_usage_workspace_id'), 'ai_usage', ['workspace_id'], unique=False)
    op.create_table('api_keys',
    sa.Column('id', apps.api.core.db_types.GUID(length=36), nullable=False),
    sa.Column('workspace_id', apps.api.core.db_types.GUID(length=36), nullable=False),
    sa.Column('created_by', apps.api.core.db_types.GUID(length=36), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('prefix', sa.String(length=20), nullable=False),
    sa.Column('key_hash', sa.String(length=64), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('last_used_at', apps.api.core.db_types.UTCDateTime(), nullable=True),
    sa.Column('created_at', apps.api.core.db_types.UTCDateTime(), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_keys_key_hash'), 'api_keys', ['key_hash'], unique=True)
    op.create_index(op.f('ix_api_keys_workspace_id'), 'api_keys', ['workspace_id'], unique=False)
    op.create_table('audit_events',
    sa.Column('id', apps.api.core.db_types.GUID(length=36), nullable=False),
    sa.Column('workspace_id', apps.api.core.db_types.GUID(length=36), nullable=False),
    sa.Column('actor_user_id', apps.api.core.db_types.GUID(length=36), nullable=True),
    sa.Column('actor_email', sa.String(length=255), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('resource_type', sa.String(length=48), nullable=False),
    sa.Column('resource_id', apps.api.core.db_types.GUID(length=36), nullable=True),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('created_at', apps.api.core.db_types.UTCDateTime(), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_events_action'), 'audit_events', ['action'], unique=False)
    op.create_index(op.f('ix_audit_events_created_at'), 'audit_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_events_workspace_id'), 'audit_events', ['workspace_id'], unique=False)
    op.create_table('projects',
    sa.Column('id', apps.api.core.db_types.GUID(length=36), nullable=False),
    sa.Column('workspace_id', apps.api.core.db_types.GUID(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_by', apps.api.core.db_types.GUID(length=36), nullable=False),
    sa.Column('created_at', apps.api.core.db_types.UTCDateTime(), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_workspace_id'), 'projects', ['workspace_id'], unique=False)
    op.create_table('roles',
    sa.Column('id', apps.api.core.db_types.GUID(length=36), nullable=False),
    sa.Column('workspace_id', apps.api.core.db_types.GUID(length=36), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'name', name='uq_roles_workspace_name')
    )
    op.create_table('notifications',
    sa.Column('id', apps.api.core.db_types.GUID(length=36), nullable=False),
    sa.Column('workspace_id', apps.api.core.db_types.GUID(length=36), nullable=False),
    sa.Column('project_id', apps.api.core.db_types.GUID(length=36), nullable=True),
    sa.Column('scan_id', apps.api.core.db_types.GUID(length=36), nullable=True),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('read', sa.Boolean(), nullable=False),
    sa.Column('created_at', apps.api.core.db_types.UTCDateTime(), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_created_at'), 'notifications', ['created_at'], unique=False)
    op.create_index(op.f('ix_notifications_read'), 'notifications', ['read'], unique=False)
    op.create_index(op.f('ix_notifications_workspace_id'), 'notifications', ['workspace_id'], unique=False)
    op.create_table('reports',
    sa.Column('id', apps.api.core.db_types.GUID(length=36), nullable=False),
    sa.Column('project_id', apps.api.core.db_types.GUID(length=36), nullable=False),
    sa.Column('type', sa.String(length=16), nullable=False),
    sa.Column('format', sa.String(length=8), nullable=False),
    sa.Column('storage_uri', sa.Text(), nullable=True),
    sa.Column('scan_ids', sa.JSON(), nullable=False),
    sa.Column('generated_by', apps.api.core.db_types.GUID(length=36), nullable=True),
    sa.Column('generated_at', apps.api.core.db_types.UTCDateTime(), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.ForeignKeyConstraint(['generated_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reports_project_id'), 'reports', ['project_id'], unique=False)
    op.create_table('role_permissions',
    sa.Column('role_id', apps.api.core.db_types.GUID(length=36), nullable=False),
    sa.Column('permission_id', apps.api.core.db_types.GUID(length=36), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'permission_id')
    )
    op.create_table('targets',
    sa.Column('id', apps.api.core.db_types.GUID(length=36), nullable=False),
    sa.Column('project_id', apps.api.core.db_types.GUID(length=36), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('value', sa.String(length=512), nullable=False),
    sa.Column('criticality', sa.String(length=16), nullable=False),
    sa.Column('added_by', apps.api.core.db_types.GUID(length=36), nullable=False),
    sa.Column('created_at', apps.api.core.db_types.UTCDateTime(), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.ForeignKeyConstraint(['added_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_targets_project_id'), 'targets', ['project_id'], unique=False)
    op.create_table('workspace_members',
    sa.Column('id', apps.api.core.db_types.GUID(length=36), nullable=False),
    sa.Column('workspace_id', apps.api.core.db_types.GUID(length=36), nullable=False),
    sa.Column('user_id', apps.api.core.db_types.GUID(length=36), nullable=False),
    sa.Column('role_id', apps.api.core.db_types.GUID(length=36), nullable=False),
    sa.Column('invited_at', apps.api.core.db_types.UTCDateTime(), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.Column('joined_at', apps.api.core.db_types.UTCDateTime(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'user_id', name='uq_workspace_members_workspace_user')
    )
    op.create_index(op.f('ix_workspace_members_user_id'), 'workspace_members', ['user_id'], unique=False)
    op.create_index(op.f('ix_workspace_members_workspace_id'), 'workspace_members', ['workspace_id'], unique=False)
    op.create_table('assets',
    sa.Column('id', apps.api.core.db_types.GUID(length=36), nullable=False),
    sa.Column('project_id', apps.api.core.db_types.GUID(length=36), nullable=False),
    sa.Column('target_id', apps.api.core.db_types.GUID(length=36), nullable=False),
    sa.Column('asset_type', sa.String(length=32), nullable=False),
    sa.Column('value', sa.String(length=512), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('first_seen', apps.api.core.db_types.UTCDateTime(), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.Column('last_seen', apps.api.core.db_types.UTCDateTime(), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_id'], ['targets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('target_id', 'asset_type', 'value', name='uq_assets_target_type_value')
    )
    op.create_index(op.f('ix_assets_project_id'), 'assets', ['project_id'], unique=False)
    op.create_index(op.f('ix_assets_target_id'), 'assets', ['target_id'], unique=False)
    op.create_table('authorization_scopes',
    sa.Column('id', apps.api.core.db_types.GUID(length=36), nullable=False),
    sa.Column('target_id', apps.api.core.db_types.GUID(length=36), nullable=False),
    sa.Column('proof_type', sa.String(length=32), nullable=False),
    sa.Column('proof_reference', sa.Text(), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('verified_by', apps.api.core.db_types.GUID(length=36), nullable=True),
    sa.Column('verified_at', apps.api.core.db_types.UTCDateTime(), nullable=True),
    sa.Column('active_testing_allowed', sa.Boolean(), nullable=False),
    sa.Column('scope_notes', sa.Text(), nullable=True),
    sa.Column('expires_at', apps.api.core.db_types.UTCDateTime(), nullable=True),
    sa.Column('created_at', apps.api.core.db_types.UTCDateTime(), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.ForeignKeyConstraint(['target_id'], ['targets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['verified_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_authorization_scopes_target_id'), 'authorization_scopes', ['target_id'], unique=False)
    op.create_table('scan_schedules',
    sa.Column('id', apps.api.core.db_types.GUID(length=36), nullable=False),
    sa.Column('workspace_id', apps.api.core.db_types.GUID(length=36), nullable=False),
    sa.Column('project_id', apps.api.core.db_types.GUID(length=36), nullable=False),
    sa.Column('target_id', apps.api.core.db_types.GUID(length=36), nullable=False),
    sa.Column('created_by', apps.api.core.db_types.GUID(length=36), nullable=False),
    sa.Column('scan_type', sa.String(length=32), nullable=False),
    sa.Column('requested_modules', sa.JSON(), nullable=False),
    sa.Column('use_ai_planner', sa.Boolean(), nullable=False),
    sa.Column('interval_minutes', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('next_run_at', apps.api.core.db_types.UTCDateTime(), nullable=False),
    sa.Column('last_run_at', apps.api.core.db_types.UTCDateTime(), nullable=True),
    sa.Column('last_scan_id', apps.api.core.db_types.GUID(length=36), nullable=True),
    sa.Column('last_error', sa.String(length=1000), nullable=True),
    sa.Column('created_at', apps.api.core.db_types.UTCDateTime(), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_id'], ['targets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scan_schedules_next_run_at'), 'scan_schedules', ['next_run_at'], unique=False)
    op.create_index(op.f('ix_scan_schedules_project_id'), 'scan_schedules', ['project_id'], unique=False)
    op.create_index(op.f('ix_scan_schedules_workspace_id'), 'scan_schedules', ['workspace_id'], unique=False)
    op.create_table('scans',
    sa.Column('id', apps.api.core.db_types.GUID(length=36), nullable=False),
    sa.Column('workspace_id', apps.api.core.db_types.GUID(length=36), nullable=False),
    sa.Column('project_id', apps.api.core.db_types.GUID(length=36), nullable=False),
    sa.Column('target_id', apps.api.core.db_types.GUID(length=36), nullable=False),
    sa.Column('initiated_by', apps.api.core.db_types.GUID(length=36), nullable=False),
    sa.Column('scan_type', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('celery_task_id', sa.String(length=255), nullable=True),
    sa.Column('execution_token', apps.api.core.db_types.GUID(length=36), nullable=True),
    sa.Column('queued_at', apps.api.core.db_types.UTCDateTime(), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=True),
    sa.Column('started_at', apps.api.core.db_types.UTCDateTime(), nullable=True),
    sa.Column('completed_at', apps.api.core.db_types.UTCDateTime(), nullable=True),
    sa.Column('created_at', apps.api.core.db_types.UTCDateTime(), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.ForeignKeyConstraint(['initiated_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_id'], ['targets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scans_project_id'), 'scans', ['project_id'], unique=False)
    op.create_index(op.f('ix_scans_target_id'), 'scans', ['target_id'], unique=False)
    op.create_index(op.f('ix_scans_workspace_id'), 'scans', ['workspace_id'], unique=False)
    op.create_table('agent_steps',
    sa.Column('id', apps.api.core.db_types.GUID(length=36), nullable=False),
    sa.Column('workspace_id', apps.api.core.db_types.GUID(length=36), nullable=False),
    sa.Column('scan_id', apps.api.core.db_types.GUID(length=36), nullable=False),
    sa.Column('step_no', sa.Integer(), nullable=False),
    sa.Column('phase', sa.String(length=32), nullable=False),
    sa.Column('action_type', sa.String(length=32), nullable=False),
    sa.Column('tool_or_module', sa.String(length=64), nullable=True),
    sa.Column('safety_tier', sa.String(length=16), nullable=True),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('result_summary', sa.Text(), nullable=True),
    sa.Column('evidence_id', apps.api.core.db_types.GUID(length=36), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', apps.api.core.db_types.UTCDateTime(), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_steps_scan_id'), 'agent_steps', ['scan_id'], unique=False)
    op.create_index(op.f('ix_agent_steps_workspace_id'), 'agent_steps', ['workspace_id'], unique=False)
    op.create_table('ai_plans',
    sa.Column('id', apps.api.core.db_types.GUID(length=36), nullable=False),
    sa.Column('scan_id', apps.api.core.db_types.GUID(length=36), nullable=False),
    sa.Column('tool_sequence', sa.JSON(), nullable=False),
    sa.Column('reasoning_summary', sa.Text(), nullable=True),
    sa.Column('model_version', sa.String(length=128), nullable=False),
    sa.Column('prompt_version', sa.String(length=64), nullable=False),
    sa.Column('created_at', apps.api.core.db_types.UTCDateTime(), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scan_id', name='uq_ai_plans_scan')
    )
    op.create_index(op.f('ix_ai_plans_scan_id'), 'ai_plans', ['scan_id'], unique=False)
    op.create_table('attack_narratives',
    sa.Column('id', apps.api.core.db_types.GUID(length=36), nullable=False),
    sa.Column('workspace_id', apps.api.core.db_types.GUID(length=36), nullable=False),
    sa.Column('scan_id', apps.api.core.db_types.GUID(length=36), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('steps', sa.JSON(), nullable=False),
    sa.Column('model_version', sa.String(length=128), nullable=True),
    sa.Column('prompt_version', sa.String(length=64), nullable=True),
    sa.Column('created_at', apps.api.core.db_types.UTCDateTime(), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scan_id', name='uq_attack_narrative_scan')
    )
    op.create_index(op.f('ix_attack_narratives_scan_id'), 'attack_narratives', ['scan_id'], unique=False)
    op.create_index(op.f('ix_attack_narratives_workspace_id'), 'attack_narratives', ['workspace_id'], unique=False)
    op.create_table('engagement_state',
    sa.Column('id', apps.api.core.db_types.GUID(length=36), nullable=False),
    sa.Column('workspace_id', apps.api.core.db_types.GUID(length=36), nullable=False),
    sa.Column('scan_id', apps.api.core.db_types.GUID(length=36), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('current_phase', sa.String(length=32), nullable=False),
    sa.Column('objective', sa.Text(), nullable=True),
    sa.Column('approval_state', sa.JSON(), nullable=False),
    sa.Column('attack_graph', sa.JSON(), nullable=False),
    sa.Column('created_at', apps.api.core.db_types.UTCDateTime(), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.Column('updated_at', apps.api.core.db_types.UTCDateTime(), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scan_id', name='uq_engagement_state_scan')
    )
    op.create_index(op.f('ix_engagement_state_scan_id'), 'engagement_state', ['scan_id'], unique=False)
    op.create_index(op.f('ix_engagement_state_workspace_id'), 'engagement_state', ['workspace_id'], unique=False)
    op.create_table('tool_runs',
    sa.Column('id', apps.api.core.db_types.GUID(length=36), nullable=False),
    sa.Column('scan_id', apps.api.core.db_types.GUID(length=36), nullable=False),
    sa.Column('tool_name', sa.String(length=64), nullable=False),
    sa.Column('tool_version', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('command_hash', sa.String(length=64), nullable=False),
    sa.Column('started_at', apps.api.core.db_types.UTCDateTime(), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.Column('completed_at', apps.api.core.db_types.UTCDateTime(), nullable=True),
    sa.Column('exit_code', sa.Integer(), nullable=True),
    sa.Column('raw_output_ref', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tool_runs_scan_id'), 'tool_runs', ['scan_id'], unique=False)
    op.create_table('vulnerabilities',
    sa.Column('id', apps.api.core.db_types.GUID(length=36), nullable=False),
    sa.Column('project_id', apps.api.core.db_types.GUID(length=36), nullable=False),
    sa.Column('asset_id', apps.api.core.db_types.GUID(length=36), nullable=True),
    sa.Column('first_detected_scan_id', apps.api.core.db_types.GUID(length=36), nullable=True),
    sa.Column('last_seen_scan_id', apps.api.core.db_types.GUID(length=36), nullable=True),
    sa.Column('fingerprint', sa.String(length=512), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('category', sa.String(length=128), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('cvss_vector', sa.String(length=128), nullable=True),
    sa.Column('cvss_score', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('status_justification', sa.Text(), nullable=True),
    sa.Column('status_changed_by', apps.api.core.db_types.GUID(length=36), nullable=True),
    sa.Column('status_changed_at', apps.api.core.db_types.UTCDateTime(), nullable=True),
    sa.Column('ai_validated', sa.Boolean(), nullable=False),
    sa.Column('ai_confidence', sa.Float(), nullable=True),
    sa.Column('created_at', apps.api.core.db_types.UTCDateTime(), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.Column('updated_at', apps.api.core.db_types.UTCDateTime(), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['first_detected_scan_id'], ['scans.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['last_seen_scan_id'], ['scans.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['status_changed_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'fingerprint', name='uq_vulnerabilities_project_fingerprint')
    )
    op.create_index(op.f('ix_vulnerabilities_project_id'), 'vulnerabilities', ['project_id'], unique=False)
    op.create_table('agent_decisions',
    sa.Column('id', apps.api.core.db_types.GUID(length=36), nullable=False),
    sa.Column('workspace_id', apps.api.core.db_types.GUID(length=36), nullable=False),
    sa.Column('scan_id', apps.api.core.db_types.GUID(length=36), nullable=False),
    sa.Column('agent_step_id', apps.api.core.db_types.GUID(length=36), nullable=True),
    sa.Column('step_no', sa.Integer(), nullable=False),
    sa.Column('phase', sa.String(length=32), nullable=False),
    sa.Column('action', sa.String(length=16), nullable=False),
    sa.Column('observations', sa.JSON(), nullable=False),
    sa.Column('inferences', sa.JSON(), nullable=False),
    sa.Column('hypotheses', sa.JSON(), nullable=False),
    sa.Column('candidates', sa.JSON(), nullable=False),
    sa.Column('selected_tool', sa.String(length=64), nullable=True),
    sa.Column('selected_confidence', sa.Float(), nullable=True),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('stop_reason', sa.String(length=64), nullable=True),
    sa.Column('budget_state', sa.JSON(), nullable=False),
    sa.Column('model_version', sa.String(length=128), nullable=True),
    sa.Column('prompt_version', sa.String(length=64), nullable=True),
    sa.Column('created_at', apps.api.core.db_types.UTCDateTime(), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.ForeignKeyConstraint(['agent_step_id'], ['agent_steps.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scan_id', 'step_no', name='uq_agent_decisions_scan_step')
    )
    op.create_index(op.f('ix_agent_decisions_scan_id'), 'agent_decisions', ['scan_id'], unique=False)
    op.create_index(op.f('ix_agent_decisions_workspace_id'), 'agent_decisions', ['workspace_id'], unique=False)
    op.create_table('attack_mappings',
    sa.Column('id', apps.api.core.db_types.GUID(length=36), nullable=False),
    sa.Column('vulnerability_id', apps.api.core.db_types.GUID(length=36), nullable=False),
    sa.Column('tactic_id', sa.String(length=16), nullable=False),
    sa.Column('tactic_name', sa.String(length=64), nullable=False),
    sa.Column('technique_id', sa.String(length=16), nullable=False),
    sa.Column('technique_name', sa.String(length=128), nullable=False),
    sa.Column('kill_chain_phase', sa.String(length=32), nullable=False),
    sa.Column('created_at', apps.api.core.db_types.UTCDateTime(), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.ForeignKeyConstraint(['vulnerability_id'], ['vulnerabilities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vulnerability_id', 'technique_id', name='uq_attack_vuln_technique')
    )
    op.create_index(op.f('ix_attack_mappings_vulnerability_id'), 'attack_mappings', ['vulnerability_id'], unique=False)
    op.create_table('compliance_mappings',
    sa.Column('id', apps.api.core.db_types.GUID(length=36), nullable=False),
    sa.Column('vulnerability_id', apps.api.core.db_types.GUID(length=36), nullable=False),
    sa.Column('framework', sa.String(length=32), nullable=False),
    sa.Column('control_id', sa.String(length=64), nullable=False),
    sa.Column('control_description', sa.Text(), nullable=True),
    sa.Column('created_at', apps.api.core.db_types.UTCDateTime(), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.ForeignKeyConstraint(['vulnerability_id'], ['vulnerabilities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vulnerability_id', 'framework', 'control_id', name='uq_compliance_vuln_framework_control')
    )
    op.create_index(op.f('ix_compliance_mappings_vulnerability_id'), 'compliance_mappings', ['vulnerability_id'], unique=False)
    op.create_table('evidence',
    sa.Column('id', apps.api.core.db_types.GUID(length=36), nullable=False),
    sa.Column('tool_run_id', apps.api.core.db_types.GUID(length=36), nullable=False),
    sa.Column('evidence_type', sa.String(length=32), nullable=False),
    sa.Column('storage_uri', sa.Text(), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=False),
    sa.Column('created_at', apps.api.core.db_types.UTCDateTime(), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.ForeignKeyConstraint(['tool_run_id'], ['tool_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidence_tool_run_id'), 'evidence', ['tool_run_id'], unique=False)
    op.create_table('remediations',
    sa.Column('id', apps.api.core.db_types.GUID(length=36), nullable=False),
    sa.Column('vulnerability_id', apps.api.core.db_types.GUID(length=36), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('steps', sa.JSON(), nullable=False),
    sa.Column('reference_links', sa.JSON(), nullable=False),
    sa.Column('generated_by', sa.String(length=16), nullable=False),
    sa.Column('model_version', sa.String(length=128), nullable=True),
    sa.Column('prompt_version', sa.String(length=64), nullable=True),
    sa.Column('created_at', apps.api.core.db_types.UTCDateTime(), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.ForeignKeyConstraint(['vulnerability_id'], ['vulnerabilities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vulnerability_id', name='uq_remediations_vulnerability')
    )
    op.create_index(op.f('ix_remediations_vulnerability_id'), 'remediations', ['vulnerability_id'], unique=False)
    op.create_table('risk_scores',
    sa.Column('id', apps.api.core.db_types.GUID(length=36), nullable=False),
    sa.Column('vulnerability_id', apps.api.core.db_types.GUID(length=36), nullable=False),
    sa.Column('business_impact_score', sa.Float(), nullable=True),
    sa.Column('asset_criticality_weight', sa.Float(), nullable=False),
    sa.Column('final_risk_score', sa.Float(), nullable=True),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('computed_at', apps.api.core.db_types.UTCDateTime(), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.ForeignKeyConstraint(['vulnerability_id'], ['vulnerabilities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vulnerability_id', name='uq_risk_scores_vulnerability')
    )
    op.create_index(op.f('ix_risk_scores_vulnerability_id'), 'risk_scores', ['vulnerability_id'], unique=False)
    op.create_table('vulnerability_evidence',
    sa.Column('vulnerability_id', apps.api.core.db_types.GUID(length=36), nullable=False),
    sa.Column('evidence_id', apps.api.core.db_types.GUID(length=36), nullable=False),
    sa.Column('tool_run_id', apps.api.core.db_types.GUID(length=36), nullable=False),
    sa.Column('created_at', apps.api.core.db_types.UTCDateTime(), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidence.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tool_run_id'], ['tool_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vulnerability_id'], ['vulnerabilities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('vulnerability_id', 'evidence_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vulnerability_evidence')
    op.drop_index(op.f('ix_risk_scores_vulnerability_id'), table_name='risk_scores')
    op.drop_table('risk_scores')
    op.drop_index(op.f('ix_remediations_vulnerability_id'), table_name='remediations')
    op.drop_table('remediations')
    op.drop_index(op.f('ix_evidence_tool_run_id'), table_name='evidence')
    op.drop_table('evidence')
    op.drop_index(op.f('ix_compliance_mappings_vulnerability_id'), table_name='compliance_mappings')
    op.drop_table('compliance_mappings')
    op.drop_index(op.f('ix_attack_mappings_vulnerability_id'), table_name='attack_mappings')
    op.drop_table('attack_mappings')
    op.drop_index(op.f('ix_agent_decisions_workspace_id'), table_name='agent_decisions')
    op.drop_index(op.f('ix_agent_decisions_scan_id'), table_name='agent_decisions')
    op.drop_table('agent_decisions')
    op.drop_index(op.f('ix_vulnerabilities_project_id'), table_name='vulnerabilities')
    op.drop_table('vulnerabilities')
    op.drop_index(op.f('ix_tool_runs_scan_id'), table_name='tool_runs')
    op.drop_table('tool_runs')
    op.drop_index(op.f('ix_engagement_state_workspace_id'), table_name='engagement_state')
    op.drop_index(op.f('ix_engagement_state_scan_id'), table_name='engagement_state')
    op.drop_table('engagement_state')
    op.drop_index(op.f('ix_attack_narratives_workspace_id'), table_name='attack_narratives')
    op.drop_index(op.f('ix_attack_narratives_scan_id'), table_name='attack_narratives')
    op.drop_table('attack_narratives')
    op.drop_index(op.f('ix_ai_plans_scan_id'), table_name='ai_plans')
    op.drop_table('ai_plans')
    op.drop_index(op.f('ix_agent_steps_workspace_id'), table_name='agent_steps')
    op.drop_index(op.f('ix_agent_steps_scan_id'), table_name='agent_steps')
    op.drop_table('agent_steps')
    op.drop_index(op.f('ix_scans_workspace_id'), table_name='scans')
    op.drop_index(op.f('ix_scans_target_id'), table_name='scans')
    op.drop_index(op.f('ix_scans_project_id'), table_name='scans')
    op.drop_table('scans')
    op.drop_index(op.f('ix_scan_schedules_workspace_id'), table_name='scan_schedules')
    op.drop_index(op.f('ix_scan_schedules_project_id'), table_name='scan_schedules')
    op.drop_index(op.f('ix_scan_schedules_next_run_at'), table_name='scan_schedules')
    op.drop_table('scan_schedules')
    op.drop_index(op.f('ix_authorization_scopes_target_id'), table_name='authorization_scopes')
    op.drop_table('authorization_scopes')
    op.drop_index(op.f('ix_assets_target_id'), table_name='assets')
    op.drop_index(op.f('ix_assets_project_id'), table_name='assets')
    op.drop_table('assets')
    op.drop_index(op.f('ix_workspace_members_workspace_id'), table_name='workspace_members')
    op.drop_index(op.f('ix_workspace_members_user_id'), table_name='workspace_members')
    op.drop_table('workspace_members')
    op.drop_index(op.f('ix_targets_project_id'), table_name='targets')
    op.drop_table('targets')
    op.drop_table('role_permissions')
    op.drop_index(op.f('ix_reports_project_id'), table_name='reports')
    op.drop_table('reports')
    op.drop_index(op.f('ix_notifications_workspace_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_read'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_created_at'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_table('roles')
    op.drop_index(op.f('ix_projects_workspace_id'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_audit_events_workspace_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_created_at'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_action'), table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_index(op.f('ix_api_keys_workspace_id'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_key_hash'), table_name='api_keys')
    op.drop_table('api_keys')
    op.drop_index(op.f('ix_ai_usage_workspace_id'), table_name='ai_usage')
    op.drop_index(op.f('ix_ai_usage_scan_id'), table_name='ai_usage')
    op.drop_index(op.f('ix_ai_usage_created_at'), table_name='ai_usage')
    op.drop_table('ai_usage')
    op.drop_table('workspaces')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_token_hash'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_mfa_recovery_codes_user_id'), table_name='mfa_recovery_codes')
    op.drop_index(op.f('ix_mfa_recovery_codes_code_hash'), table_name='mfa_recovery_codes')
    op.drop_table('mfa_recovery_codes')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('permissions')
    # ### end Alembic commands ###
