"""add authorization_scopes table

Revision ID: 90c242a2cfe1
Revises: 6a99a2128bba
Create Date: 2026-07-24 10:53:28.966362

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90c242a2cfe1'
down_revision: Union[str, None] = '6a99a2128bba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('authorization_scopes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('target_id', sa.UUID(), nullable=False),
    sa.Column('proof_type', sa.String(length=32), nullable=False),
    sa.Column('proof_reference', sa.Text(), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('verified_by', sa.UUID(), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('active_testing_allowed', sa.Boolean(), nullable=False),
    sa.Column('scope_notes', sa.Text(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['target_id'], ['targets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['verified_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_authorization_scopes_target_id'), 'authorization_scopes', ['target_id'], unique=False)
    # ### end Alembic commands ###

    # Same RLS pattern as `targets` (see 87ca3d89a924), one join hop further:
    # authorization_scopes -> targets -> projects.workspace_id.
    op.execute("ALTER TABLE authorization_scopes ENABLE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE authorization_scopes FORCE ROW LEVEL SECURITY")
    op.execute(
        "CREATE POLICY workspace_isolation ON authorization_scopes USING ("
        "target_id IN ("
        "SELECT t.id FROM targets t JOIN projects p ON p.id = t.project_id "
        "WHERE p.workspace_id = current_setting('app.current_workspace_id', true)::uuid"
        "))"
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_authorization_scopes_target_id'), table_name='authorization_scopes')
    op.drop_table('authorization_scopes')
    # ### end Alembic commands ###
