"""add reports table

Revision ID: c0ecf2f76c48
Revises: ccf0f32c1190
Create Date: 2026-07-27 13:11:13.968087

"""
import uuid
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy.sql import column, table

# revision identifiers, used by Alembic.
revision: str = 'c0ecf2f76c48'
down_revision: Union[str, None] = 'ccf0f32c1190'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

_permissions = table("permissions", column("id", sa.UUID()), column("key", sa.String()), column("description", sa.Text()))
_role_permissions = table("role_permissions", column("role_id", sa.UUID()), column("permission_id", sa.UUID()))

_NEW_PERMISSIONS = [
    ("report:create", "Generate reports"),
    ("report:read", "View and download reports"),
]
# read for everyone; generation for owner/admin (an export/deliverable action).
_ROLE_GRANTS = {
    "report:create": ["owner", "admin"],
    "report:read": ["owner", "admin", "member"],
}


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(length=16), nullable=False),
    sa.Column('format', sa.String(length=8), nullable=False),
    sa.Column('storage_uri', sa.Text(), nullable=True),
    sa.Column('scan_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('generated_by', sa.UUID(), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['generated_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reports_project_id'), 'reports', ['project_id'], unique=False)
    # ### end Alembic commands ###

    # RLS via project -> workspace (same ENABLE+FORCE pattern as prior steps).
    op.execute("ALTER TABLE reports ENABLE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE reports FORCE ROW LEVEL SECURITY")
    op.execute(
        "CREATE POLICY workspace_isolation ON reports USING ("
        "project_id IN (SELECT id FROM projects WHERE workspace_id = "
        "current_setting('app.current_workspace_id', true)::uuid))"
    )

    # Seed report:create / report:read permissions.
    bind = op.get_bind()
    perm_ids = {key: uuid.uuid4() for key, _ in _NEW_PERMISSIONS}
    op.bulk_insert(
        _permissions, [{"id": perm_ids[k], "key": k, "description": d} for k, d in _NEW_PERMISSIONS]
    )
    role_rows = bind.execute(sa.text("SELECT id, name FROM roles WHERE workspace_id IS NULL")).fetchall()
    role_ids = {name: rid for rid, name in role_rows}
    op.bulk_insert(
        _role_permissions,
        [
            {"role_id": role_ids[r], "permission_id": perm_ids[k]}
            for k, roles in _ROLE_GRANTS.items()
            for r in roles
            if r in role_ids
        ],
    )


def downgrade() -> None:
    keys = ", ".join(f"'{k}'" for k, _ in _NEW_PERMISSIONS)
    op.execute(
        f"DELETE FROM role_permissions WHERE permission_id IN (SELECT id FROM permissions WHERE key IN ({keys}))"
    )
    op.execute(f"DELETE FROM permissions WHERE key IN ({keys})")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reports_project_id'), table_name='reports')
    op.drop_table('reports')
    # ### end Alembic commands ###
