"""add risk_scores, compliance_mappings, target criticality

Revision ID: ccf0f32c1190
Revises: 104dc6463258
Create Date: 2026-07-27 12:47:27.412800

"""
import uuid
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import column, table


# revision identifiers, used by Alembic.
revision: str = 'ccf0f32c1190'
down_revision: Union[str, None] = '104dc6463258'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

_permissions = table("permissions", column("id", sa.UUID()), column("key", sa.String()), column("description", sa.Text()))
_role_permissions = table("role_permissions", column("role_id", sa.UUID()), column("permission_id", sa.UUID()))


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('compliance_mappings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('vulnerability_id', sa.UUID(), nullable=False),
    sa.Column('framework', sa.String(length=32), nullable=False),
    sa.Column('control_id', sa.String(length=64), nullable=False),
    sa.Column('control_description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['vulnerability_id'], ['vulnerabilities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vulnerability_id', 'framework', 'control_id', name='uq_compliance_vuln_framework_control')
    )
    op.create_index(op.f('ix_compliance_mappings_vulnerability_id'), 'compliance_mappings', ['vulnerability_id'], unique=False)
    op.create_table('risk_scores',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('vulnerability_id', sa.UUID(), nullable=False),
    sa.Column('business_impact_score', sa.Float(), nullable=True),
    sa.Column('asset_criticality_weight', sa.Float(), nullable=False),
    sa.Column('final_risk_score', sa.Float(), nullable=True),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['vulnerability_id'], ['vulnerabilities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vulnerability_id', name='uq_risk_scores_vulnerability')
    )
    op.create_index(op.f('ix_risk_scores_vulnerability_id'), 'risk_scores', ['vulnerability_id'], unique=False)
    # server_default so existing target rows get a value; NOT NULL is safe.
    op.add_column(
        'targets',
        sa.Column('criticality', sa.String(length=16), nullable=False, server_default='medium'),
    )
    # ### end Alembic commands ###

    # RLS: both tables scope through vulnerabilities -> projects.workspace_id
    # (same ENABLE+FORCE pattern as prior steps). The worker sets
    # app.current_workspace_id before writing during a scan.
    for tbl in ("risk_scores", "compliance_mappings"):
        op.execute(f"ALTER TABLE {tbl} ENABLE ROW LEVEL SECURITY")
        op.execute(f"ALTER TABLE {tbl} FORCE ROW LEVEL SECURITY")
        op.execute(
            f"CREATE POLICY workspace_isolation ON {tbl} USING ("
            "vulnerability_id IN (SELECT v.id FROM vulnerabilities v JOIN projects p ON p.id = v.project_id "
            "WHERE p.workspace_id = current_setting('app.current_workspace_id', true)::uuid))"
        )

    # Seed the target:update permission (setting business criticality). Same
    # roles as target:create: owner/admin/member.
    bind = op.get_bind()
    perm_id = uuid.uuid4()
    op.bulk_insert(
        _permissions,
        [{"id": perm_id, "key": "target:update", "description": "Update a target's business criticality"}],
    )
    role_rows = bind.execute(sa.text("SELECT id, name FROM roles WHERE workspace_id IS NULL")).fetchall()
    role_ids = {name: rid for rid, name in role_rows}
    op.bulk_insert(
        _role_permissions,
        [{"role_id": role_ids[r], "permission_id": perm_id} for r in ("owner", "admin", "member") if r in role_ids],
    )


def downgrade() -> None:
    op.execute(
        "DELETE FROM role_permissions WHERE permission_id IN (SELECT id FROM permissions WHERE key = 'target:update')"
    )
    op.execute("DELETE FROM permissions WHERE key = 'target:update'")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('targets', 'criticality')
    op.drop_index(op.f('ix_risk_scores_vulnerability_id'), table_name='risk_scores')
    op.drop_table('risk_scores')
    op.drop_index(op.f('ix_compliance_mappings_vulnerability_id'), table_name='compliance_mappings')
    op.drop_table('compliance_mappings')
    # ### end Alembic commands ###
