"""add ai_plans table

Revision ID: 104dc6463258
Revises: bbcddc51e96a
Create Date: 2026-07-27 05:42:28.553807

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '104dc6463258'
down_revision: Union[str, None] = 'bbcddc51e96a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_plans',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('scan_id', sa.UUID(), nullable=False),
    sa.Column('tool_sequence', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('reasoning_summary', sa.Text(), nullable=True),
    sa.Column('model_version', sa.String(length=128), nullable=False),
    sa.Column('prompt_version', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_plans_scan_id'), 'ai_plans', ['scan_id'], unique=False)
    # ### end Alembic commands ###

    # RLS via scans.workspace_id (scans itself is RLS-exempt; see step 4). The AI
    # planner runs inside the orchestrator where app.current_workspace_id is set.
    op.execute("ALTER TABLE ai_plans ENABLE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE ai_plans FORCE ROW LEVEL SECURITY")
    op.execute(
        "CREATE POLICY workspace_isolation ON ai_plans USING ("
        "scan_id IN (SELECT id FROM scans WHERE workspace_id = "
        "current_setting('app.current_workspace_id', true)::uuid))"
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ai_plans_scan_id'), table_name='ai_plans')
    op.drop_table('ai_plans')
    # ### end Alembic commands ###
